"""Consts."""

DOMAIN = "thames_water"
DEFAULT_LITER_COST = 0.0030682
MIN_LITER_COST = 0.00005
MAX_LITER_COST = 1.0
NEXT_LITER_COST_KEY = "next_liter_cost"
NEXT_LITER_COST_START_DATE_KEY = "next_liter_cost_start_date"
RATE_REMINDER_DAYS_KEY = "rate_reminder_days"
DEFAULT_RATE_REMINDER_DAYS = 60
MIN_RATE_REMINDER_DAYS = 1
MAX_RATE_REMINDER_DAYS = 365
